### ISSUE TITLE
Events_since1980.json is missing in the data file, and where can I get the trained temporal models?Thanks!

### ISSUE THREAD

**Issue by q876066285** [guyrosin/event_driven_qe#2]

**Comment by guyrosin** [comment]
Sorry for the late reply - I've just committed the missing data file. (thanks!)

You can download the word embeddings used in the paper from this link (see the README for more details): https://karpef.cs.technion.ac.il/index.php/s/YA3G3iqDZyagnFH/download

Let me know if you have any more questions!

**Comment by q876066285** [comment]
Thank you for your reply!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "guyrosin/event_driven_qe"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月13日(星期六) 凌晨3:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [guyrosin/event_driven_qe] Events_since1980.json is missing in the data file, and where can I get the trained temporal models?Thanks! (Issue #2)





 
Sorry for the late reply - I've just committed the missing data file. (thanks!)
 
You can download the word embeddings used in the paper from this link (see the README for more details): https://karpef.cs.technion.ac.il/index.php/s/YA3G3iqDZyagnFH/download
 
Let me know if you have any more questions!
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
